JotForm.newDefaultTheme = true;
	JotForm.extendsNewTheme = false;
	JotForm.singleProduct = false;
	JotForm.newPaymentUIForNewCreatedForms = false;
	JotForm.newPaymentUI = true;
	JotForm.submitError="jumpToFirstError";

	JotForm.init(function(){
	/*INIT-START*/
if (window.JotForm && JotForm.accessible) $('input_99').setAttribute('tabindex',0);
      setTimeout(function() {
          $('input_6').hint('ex: myname@example.com');
       }, 20);
if (window.JotForm && JotForm.accessible) $('input_57').setAttribute('tabindex',0);
      JotForm.setPhoneMaskingValidator( 'input_25_full', '\u0028\u0023\u0023\u0029 \u0023 \u0023\u0023\u0023\u0023\u002d\u0023\u0023\u0023\u0023' );
if (window.JotForm && JotForm.accessible) $('input_100').setAttribute('tabindex',0);
if (window.JotForm && JotForm.accessible) $('input_60').setAttribute('tabindex',0);
	/*INIT-END*/
	});

   JotForm.prepareCalculationsOnTheFly([null,{"name":"clickTo","qid":"1","text":"Cadastro do Estudante","type":"control_head"},null,null,null,null,{"name":"studentEmail6","qid":"6","subLabel":"exemplo@exemplo.com","text":"Email","type":"control_email"},null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,{"name":"birthDate24","qid":"24","text":"Data de Nascimento","type":"control_birthdate"},{"name":"phoneNumber25","qid":"25","text":"Numero de Telefone","type":"control_phone"},null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,{"name":"curso","qid":"46","text":"Curso","type":"control_dropdown"},null,null,null,null,null,null,{"description":"","name":"nome","qid":"53","text":"Nome","type":"control_fullname"},{"description":"","name":"turma","qid":"54","subLabel":"","text":"Turma","type":"control_dropdown"},null,null,{"description":"","name":"matricula","qid":"57","subLabel":"","text":"Matricula","type":"control_textbox"},null,null,{"description":"","name":"digiteSua","qid":"60","subLabel":"","text":"Digite sua contestacao a seguir:","type":"control_textarea"},{"description":"","name":"selecioneA","qid":"61","subLabel":"","text":"Selecione a opcao que se encaixa na sua contestacao:","type":"control_dropdown"},null,null,null,null,{"name":"quebraDe73","qid":"66","text":"Quebra de Pagina","type":"control_pagebreak"},null,null,{"description":"","name":"email","qid":"69","subLabel":"exemplo@exemplo.com","text":"E-mail","type":"control_email"},null,null,null,{"name":"realizarLogin","qid":"73","text":"Realizar login","type":"control_head"},null,null,null,null,null,null,null,null,null,{"name":"enviar","qid":"83","text":"Enviar","type":"control_button"},null,null,null,null,null,null,null,null,null,null,null,null,null,{"name":"quebraDe","qid":"97","text":"Quebra de Pagina","type":"control_pagebreak"},{"name":"quebraDe98","qid":"98","text":"Quebra de Pagina","type":"control_pagebreak"},{"description":"","name":"insiraA99","qid":"99","subLabel":"","text":"Insira a senha","type":"control_textbox"},{"description":"","name":"outros","qid":"100","subLabel":"","text":"Outros:","type":"control_textbox"}]);
   setTimeout(function() {
JotForm.paymentExtrasOnTheFly([null,{"name":"clickTo","qid":"1","text":"Cadastro do Estudante","type":"control_head"},null,null,null,null,{"name":"studentEmail6","qid":"6","subLabel":"exemplo@exemplo.com","text":"Email","type":"control_email"},null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,{"name":"birthDate24","qid":"24","text":"Data de Nascimento","type":"control_birthdate"},{"name":"phoneNumber25","qid":"25","text":"Numero de Telefone","type":"control_phone"},null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,{"name":"curso","qid":"46","text":"Curso","type":"control_dropdown"},null,null,null,null,null,null,{"description":"","name":"nome","qid":"53","text":"Nome","type":"control_fullname"},{"description":"","name":"turma","qid":"54","subLabel":"","text":"Turma","type":"control_dropdown"},null,null,{"description":"","name":"matricula","qid":"57","subLabel":"","text":"Matricula","type":"control_textbox"},null,null,{"description":"","name":"digiteSua","qid":"60","subLabel":"","text":"Digite sua contestacao a seguir:","type":"control_textarea"},{"description":"","name":"selecioneA","qid":"61","subLabel":"","text":"Selecione a opcao que se encaixa na sua contestacao:","type":"control_dropdown"},null,null,null,null,{"name":"quebraDe73","qid":"66","text":"Quebra de Pagina","type":"control_pagebreak"},null,null,{"description":"","name":"email","qid":"69","subLabel":"exemplo@exemplo.com","text":"E-mail","type":"control_email"},null,null,null,{"name":"realizarLogin","qid":"73","text":"Realizar login","type":"control_head"},null,null,null,null,null,null,null,null,null,{"name":"enviar","qid":"83","text":"Enviar","type":"control_button"},null,null,null,null,null,null,null,null,null,null,null,null,null,{"name":"quebraDe","qid":"97","text":"Quebra de Pagina","type":"control_pagebreak"},{"name":"quebraDe98","qid":"98","text":"Quebra de Pagina","type":"control_pagebreak"},{"description":"","name":"insiraA99","qid":"99","subLabel":"","text":"Insira a senha","type":"control_textbox"},{"description":"","name":"outros","qid":"100","subLabel":"","text":"Outros:","type":"control_textbox"}]);}, 20); 
